version: '2'

services:
  openssh-server:
    build: ./
    hostname: spectre-ssh
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - PASSWORD_ACCESS=true
      - USER_NAME=developer
      - USER_PASSWORD=dev
    ports:
      - 2222:2222
