name: Gem Push

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4'
        bundler-cache: true

    - name: Check code style
      run: bundle exec rubocop

    - name: Run tests
      run: bundle exec rspec

    - name: Build GEM
      run: bundle exec gem build

    - name: Publish to GitHub Packages
      run: gem push --host https://rubygems.pkg.github.com/${OWNER} *.gem
      env:
        OWNER: ${{ github.repository_owner }}
        GEM_HOST_API_KEY: "Bearer ${{secrets.GITHUB_TOKEN}}"

